### ISSUE TITLE
Error message appearing after updating R  

### ISSUE THREAD

**Issue by martinig** [bbolker/nlme#1]
I'm using a few of your packages, so I am not entirely sure which issues page is best suited for it. 

I am using `lme4::ranef` to pull out random effects values for a `nlme` model. When I run my script in R version 4.0.5 the code listed below works fine and doesn't give any errors. However, when I run the same script in R version 4.1.3, I get the following error:

`Error in as.data.frame.ranef.lme(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) :  'optional' argument not implemented In addition: Warning message: In tidy.lme(nlme.arc) : ran_pars not yet implemented for nonlinear models.`

Here is the part of my script that is giving the error:
```
nlme.arc=nlme(wt ~ (B*atan(k*(age - mx)) + my), #Function
	data=dfs[[i]], #Input dataset (part of a for loop)
fixed=B+k+mx+my~1, 
	random=list(squirrel_id = pdDiag(B+k+mx+my~1)), 
   	start=c(B=arc_A_est, k=arc_k_est, mx=arc_mx_est, my=arc_my_est), 
   	na.action=na.omit, #Omit any NA values
	control=nlmeControl(maxIter=200, pnlsMaxIter=10, msMaxIter=100)) 
summary(nlme.arc)
arc_ran  <- data.frame(lme4::ranef(nlme.arc)) #here is the line 
s_pmod[(1+mod_num*(i-1)), 'ran_B_max']  <- max(arc_ran$B) #Extracts and appends to dataset
s_pmod[(1+mod_num*(i-1)), 'ran_B_min']  <- min(arc_ran$B)
```

**Comment by bbolker** [comment]
OK, I think I see what's going on here.  In the meantime, `as.data.frame(ranef(nlme.arc))` should work fine.

```r
library(nlme)
library(broom.mixed)
fm1 <- nlme(height ~ SSasymp(age, Asym, R0, lrc),
                 data = Loblolly,
                 fixed = Asym + R0 + lrc ~ 1,
                 random = Asym ~ 1,
                 start = c(Asym = 103, R0 = -8.5, lrc = -3.3))
rr <- ranef(fm1)
try(data.frame(rr))
as.data.frame(rr)
```

**Comment by bbolker** [comment]
This is resolved in the development version (and, `as.data.frame()` should work fine). Couldn't track down the change in R that made it stop working. `remotes::install_github("bbolker/broom.mixed")` if you want to take it for a spin.

**Comment by martinig** [comment]
That worked! Thanks, Ben.
